name: Robot Framework Tests
on:
  [push,workflow_dispatch]
jobs:
  test:
    name: WEB test com Robot Framework
    runs-on: ubuntu-24.04
    steps:
      - name: Clonar arquivo do repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+")
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -q "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver


      - name: Instalar dependências
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-faker
          pip install robotframework-seleniumlibrary
         

      - name: Executando os testes WEB Robot Framework
        run: |
          robot --outputdir logs/ .

      - name: Garantir index.html para GitHub Pages
        run: cp logs/log.html logs/index.html

      - name: Test Report
        uses: actions/upload-artifact@v4  
        if: always()
        with:
          name: robot-framework-report
          path: logs

  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-24.04
    if: always() # Executa mesmo se o job de teste falhar
    needs: 
      - test
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://clislania.github.io/The-originals-academyt14-front-robot # Substitua pelo seu usuário e repositório
      
    steps:
      - name: Setup pages
        uses: actions/configure-pages@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          name: robot-framework-report
          path: results/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: results/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        


  # robot:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python 3.11
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.11
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install robotframework
  #     - name: Run Robot Framework tests
  #       run: |
  #         robot tests/
  #     - name: Upload Robot Framework results
  #       if: always()
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: robot-results
